//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApplicants.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files_Adjunt
    {
        public int Consecutive { get; set; }
        public int Id_Applicant { get; set; }
        public string File_Name { get; set; }
        public string Tipe_File { get; set; }
        public decimal Size { get; set; }
        public string Path_File_Local { get; set; }
        public string Path_File_URL { get; set; }
        public string Description_File { get; set; }
    }
}
